### ISSUE TITLE
VCL porting helper lib

### ISSUE THREAD

**Issue by tbrannam** [fastly/compute-starter-kit-assemblyscript-default#14]
Are there plans to expand the functions exposed by as-compute?  

There are a number of functions in VCL that would simplify expressing some ideas in assemblyscript, such as randomint_seeded, or digest.md5?

**Comment by torch2424** [comment]
@tbrannam Hello! :smile: 

Thanks for reaching out! Stoked to hear you are using as-compute (and it's going well? :smile: )

> There are a number of functions in VCL that would simplify expressing some ideas in assemblyscript, such as randomint_seeded, or digest.md5?

Ah! So this wasn't something we had planned, but definitely, I can bring this up with me team, and something we can consider doing! :smile:
