### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by hellatan** [fastly/compute-starter-kit-assemblyscript-default#16]
The `using Compute@Edge`, `VCL migration`, and `fastly backend create` links in the README need the `https://developer.fastly.com/` host. Right now they only link to the github repo which ends up being a 404.

**Comment by torch2424** [comment]
@hellatan Ah! Thank you so much for the issue! I'll open a PR for this now! 😄

**Comment by hellatan** [comment]
i probably could have done that but i'm not working at 💯 atm so i gotta cut corners somewhere 😂

**Comment by torch2424** [comment]
No worries at all @hellatan ! 😄
